;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        py-electric-backspace
        python-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        clipboard-kill-region
        expand-and-mark-next
        handle-switch-frame
        scroll-up-command
        ))
